# Generated by Django 2.2 on 2021-06-16 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login_app', '0001_initial'),
        ('the_wall_app', '0004_auto_20210615_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_likes',
            field=models.ManyToManyField(related_name='liked_posts', to='login_app.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comments', to='the_wall_app.Message'),
        ),
        migrations.AlterField(
            model_name='message',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_messages', to='login_app.User'),
        ),
    ]
