# Generated by Django 2.2 on 2021-06-16 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('the_wall_app', '0006_auto_20210615_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='user_likes',
            field=models.ManyToManyField(related_name='liked_posts', to='login_app.User'),
        ),
    ]
